-- 1. What are the distinct factory names in the dataset?
-- 2. What are the distinct industry types represented?
-- 3. What is the total number of employees for each factory over all years?
-- 4. Which factories had more than 1000 employees in the year 2024?
-- 5. What data is recorded for all factories in the year 2024?
-- 6. Which factories have an average defect rate below 0.05 over all years?
-- 7. Which factories experienced more than 10 safety incidents in any year?
-- 8. Which factories implemented lean manufacturing practice in any year?
-- 9. Which factories consumed over 1,000,000 kWh energy in any year?
-- 10. Which factories had 'Advanced' production technology in any year?
-- 11. How many factories are there per industry type?
-- 12. What is the maximum number of employees any factory had in any year?
-- 13. What is the overall average defect rate across all factories and years?
-- 14. What is the total number of units produced by all factories in 2024?
-- 15. Which factory has the lowest average energy efficiency over 4 years?
-- 16. What is the total defective units produced by each factory over all years?
-- 17. Which factories have an average defect rate below 0.05 over all years?
-- 18. How many years of data are available for each factory?
-- 19. Which factories produced more than 20,000 units in 2024?
-- 20. Which factories have average employee satisfaction above 5?
-- 21. What are the top 5 factories by total units produced in 2024?
-- 22. What factories have the lowest defect rate in 2024?
-- 23. Which factories have the highest employee performance in 2024?
-- 24. Which factories consumed the highest energy in 2024?
-- 25. Which factories generated the least waste in 2024?
-- 26. Which factories have names containing 'Global' in any year?
-- 27. Which factories have a non-null quality certification in any year?
-- 28. Which factories have production technology level starting with 'B' in any year?
-- 29. Which factories have 'High' automation level in any year?
-- 30. Which factories have 'ISO' in their quality certification in any year?
