-- 1. List all factory names and locations.

-- 2. Show factories producing more than 20,000 units.

-- 3. Factories with no safety incidents.

-- 4. Factories with employee satisfaction under 5.

-- 5. Fact rows where defective_units > 5% of total units.

-- 6. Total units produced per factory.

-- 7. Average employee satisfaction by industry type.

-- 8. Max, min, average defect rate by year.

-- 9. Count distinct factories by certification.

-- 10. Sum maintenance cost grouped by factory size.

-- 11. Most productive factories per year (ranking).

-- 12. Average overtime hours by shift type.

-- 13. Running total of total units produced, ordered by year.

-- 14. Factories with below average energy efficiency per year.

-- 15. Factories with machine downtime hours above average per year.

-- 16. Count factories per safety incident category.

-- 17. Average defect rate for ISO 9001 vs other certifications.

-- 18. Total waste generated by shift type in large factories.

-- 19. Classify production efficiency using cost_per_unit_idr.

-- 20. Factories where overtime > 10% of total hours worked.

-- 21. Rank factories by total defective units.

-- 22. Cumulative energy consumed per factory over years.

-- 23. Average defect rate by production line and safety incident level.

-- 24. Average employee satisfaction by factory size and year.

-- 25. Average cost per unit per year.

-- 26. Factories with defect rate greater than 0.05.

-- 27. Number of factories per shift type per year.

-- 28. Average maintenance cost per industry type.

-- 29. Factories where safety incidents are Medium or High.

-- 30. Top 3 factories with highest average employee performance.

-- 31. Factories with negative or zero waste (if any).

-- 32. Factories with safety incidents classified as High.

-- 33. Average overtime hours for factories with 'Mixed' shift.

-- 34. Minimum employee satisfaction per factory.

-- 35. Average machine downtime hours per production line.

-- 36. Factories with energy efficiency below 0.05 kWh/unit.

-- 37. Total operational and maintenance costs per factory.

-- 38. Factories with employee performance score above 0.9.

-- 39. Factories with no defects.

-- 40. Average total hours worked grouped by certification.

-- 41. Factories ranked by total units produced overall.

-- 42. Year-over-year change in employee satisfaction per factory.

-- 43. Factories with increasing employee satisfaction vs previous year.

-- 44. Average defect rate per year and shift type.

-- 45. Top 5 highest machine downtime hours recorded.

-- 46. Factories with defective units above 90th percentile.

-- 47. Median employee satisfaction by industry.

-- 48. Average waste generated per factory size category.

-- 49. Total defective units and average defect rate per year.

-- 50. Factories with above average employee satisfaction and below average defect rate.
