CREATE TABLE public.factory_data (
	factory_id int4 NULL,
	factory_name varchar(50) NULL,
	industry_type varchar(50) NULL,
	number_of_employees int4 NULL,
	production_technology_level varchar(50) NULL,
	quality_certification varchar(50) NULL,
	supply_chain_integration varchar(50) NULL,
	lean_manufacturing_practice varchar(50) NULL,
	maintenance_strategy varchar(50) NULL,
	six_sigma_maturity_level varchar(50) NULL,
	automation_level varchar(50) NULL,
	employee_training_program varchar(50) NULL,
	"year" int4 NULL,
	total_units_produced int4 NULL,
	defective_units int4 NULL,
	total_hours_worked int4 NULL,
	overtime_hours int4 NULL,
	energy_consumed_kwh int4 NULL,
	safety_incidents int4 NULL,
	employee_performance float4 NULL,
	defect_rate float4 NULL,
	energy_efficiency_kwh_per_unit varchar(50) NULL,
	employee_satisfaction int4 NULL,
	machine_downtime_hours int4 NULL,
	waste_generated_kg int4 NULL
);
